export default {
  spacings: {
    none: "0",
    xxs: ".25rem",
    xs: ".5rem",
    sm: "1rem",
    md: "1.5rem",
    lg: "1.8rem",
    xl: "2.25rem",
    "2xl": "4rem",
    "3xl": "6rem",
    "4xl": "9rem",
    auto: "auto",
    printMargin: "75px",
  },
  colors: {
    primaryTextColor: "#333333",
    secondaryTextColor: "#8a8a8a",
    background: "#f4f4f4",
    primary: "#3F78B1",
    danger: "#FF4E4E",
    dangerBackground: "#fff6f2 !important",
    dangerSaturated: "#FF4E4E",
    placeholder: "#ABABAB",
    warning: "#FF9900",
    success: "#7CC924",

    orange: "#FFC62A",
    lightBlue: "#E3ECF6",
    blue: "#94B2D1",
    darkBlue: "#2474C9",
    green: "#C0F5A2",
    lightGray: "#F2F2F2",
    gray: "#CCCCCC",
    darkerGray: "#8c8c8c",
    dark: "#1A1A1A",
    white: "#FFF",
    yellow: "#FEBA3E",
  },
  borders: {
    light: "#CCCCCC",
  },
  buttons: {
    background: "#3F78B1",
    text: "#ffffff",
    secondaryBackground: "#a7a7a7",
    secondaryText: "#ffffff",
    success: "#8ACC3F",
    danger: "#FF4E4E",
  },
  textSizes: {
    xs: "0.8333rem",
    sm: "1rem",
    md: "1.167rem",
    lg: "1.333rem",
    xl: "1.5rem",
    "2xl": "1.667rem",
    "3xl": "2rem",
    "4xl": "2.5rem",
  },
};
